version: '3.4'

volumes: 
    datafile:

networks: 
    portalnetwork:
        driver: bridge


services:

    db:
        image: mysql
        container_name: mysqldb
        volumes: 
            - datafile:/var/lib/mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: database
        networks: 
            - portalnetwork

    core-api:
        build: 
            context: .
            dockerfile: Dockerfile
        depends_on: 
            - db
        container_name: WebAPI
        ports: 
            - "56562:80"
        restart: always
        environment: 
            - DBHOST= db
        networks: 
            - portalnetwork

    web:
        build: 
            context: .
            dockerfile: Dockerfile.web
        container_name: WebApp
        ports: 
            - "56551:56551"
        restart: always
        networks: 
            - portalnetwork
        environment: 
            - core=http://core-api/api/
            


